# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: restoreBuildProjects
    displayName: Solution(s) to restore and build
    type: string
    default: '*.sln'
    values:
      - '*.sln'
      - '**/*.sln'

variables:
  projectkey: qckdev.AspNetCore.Identity
  projectName: qckdev.AspNetCore.Identity
  buildConfiguration: 'Release'

steps:

#- task: ProjectVarReader@0
#  inputs:
#    searchPattern: '**/$(ProjectName).??proj'
#    displayName: $(MainProject.Version)
#    variablePrefix: 'MainProject'
#    propertyName: 'Version'

- task: PowerShell@2
  displayName: $(MainProject.Version)
  inputs:
    targetType: 'inline'
    script: |
      $xml = [Xml] (Get-Content '**/$(ProjectName).??proj')
      $version = $xml.Project.PropertyGroup.Version
      write-output "Version: $version"
      echo "##vso[task.setvariable variable=MainProject_Version]$version"

- task: PowerShell@2
  displayName: $(MainProject.Version) v2
  inputs:
    targetType: 'inline'
    script: |
      $xml = [Xml] (Get-Content '**/$(ProjectName).??proj')
      $version = $xml.Project.PropertyGroup.Version
      write-output "Vesion: $version"
      echo "##vso[task.setvariable variable=MainProject2.Version]$version"

- task: PowerShell@2
  displayName: 'Export variable list'
  inputs:
    targetType: 'inline'
    script: |
      $var = (gci env:*).GetEnumerator() | Sort-Object Name
      $out = ""
      Foreach ($v in $var) {$out = $out + "`t{0,-28} = {1,-28}`n" -f $v.Name, $v.Value}
      
      $fileName = Join-Path $env:BUILD_ARTIFACTSTAGINGDIRECTORY "variable-list.md"
      write-output "dump variables on $fileName"
      set-content $fileName $out
   
      write-output "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Environment Variables;]$fileName"

- task: PowerShell@2
  displayName: 'Get projects'
  inputs:
    targetType: 'inline'
    script: |
      $files = Get-ChildItem -recurse "$(Parameters.RestoreBuildProjects)"
      write-output $files

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'hfrances-github'
    scannerMode: 'MSBuild'
    projectKey: '$(ProjectKey)'
    projectName: '$(ProjectName)'
    projectVersion: '$(MainProject.Version)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'