# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectkey: qckdev.AspNetCore.Identity
  projectName: qckdev.AspNetCore.Identity
  buildConfiguration: 'Release'

parameters:
  - name: restoreBuildProjects
    type: string
    default: '**/*.sln'

steps:
#- task: DotNetCoreCLI@2
#  displayName: Restore
#  inputs:
#    command: restore
#    projects: '$(Parameters.RestoreBuildProjects)'
- task: ProjectVarReader@0
  inputs:
    searchPattern: '**\$(ProjectName).??proj'
    variablePrefix: 'MainProject'
    propertyName: 'Version'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'hfrances-github'
    scannerMode: 'MSBuild'
    projectKey: '$(ProjectKey)'
    projectName: '$(ProjectName)'
    projectVersion: '$(MainProject.Version)'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'